# Changes here will be overwritten by Copier
_commit: 2.6.0
_src_path: gh:DiamondLightSource/python-copier-template
author_email: callum.forrester@diamond.ac.uk
author_name: Callum Forrester
component_lifecycle: experimental
component_owner: group:default/sscc
component_type: library
description: STOMP integration for bluesky
distribution_name: bluesky-stomp
docker: false
docs_type: README
git_platform: github.com
github_org: DiamondLightSource
package_name: bluesky_stomp
pypi: true
repo_name: bluesky-stomp
type_checker: pyright
